### PR TITLE
bootstrap v4, restructure repo

### PR DESCRIPTION
**Pull request by seanbreckenridge**
still a WIP, just pushing progress

### CODE REVIEW

**Comment by janvernieuwe** [comment]
With v3 beeing discontinued next month, would be nice to be able to upgrade to a v4.
@abhinavk99 are you still maintaining this repo?

**Comment by abhinavk99** [comment]
> With v3 beeing discontinued next month, would be nice to be able to upgrade to a v4.
> @abhinavk99 are you still maintaining this repo?

Hi @janvernieuwe, unfortunately I don't have the free time to rewrite jikanpy for v4, so it'd be great if someone who sees this contribute.

**Comment by Chris-Peterson444** [comment]
@seanbreckenridge are you still planning on working on this? Otherwise, I'd like to take a swing at updating this to v4 without the auto code generation.

**Comment by seanbreckenridge** [comment]
Since the auto code generator didn't work I don't plan to any time soon

Go ahead

**Comment by Chris-Peterson444** [comment]
@seanbreckenridge we can probably close this out since we've released v4. Unless you'd like to keep it open for potential future work.

**Pull request closed without merging**
